### DISCUSSION TITLE
Define multiple mock calls for the same endpoint

### DISCUSSION THREAD

**Discussion by mamdouni** [Decathlon/tzatziki#67] [Ideas]
Hello,

I think that this will be an important feature to add to Tzatziki. Actually we cannot mock multiple calls with an endpoint. Here's an example : 
```
Given that "/backend/endpoint" is mocked as:
    """yaml
      request:
        method: GET
      response:
        status: PARTIAL_CONTENT
        body:
          payload:
            - 8067
            - 8068
            - 8069
        headers:
          X-Total-Count: 4
    """
And that "/backend/endpoint" is mocked as:
    """yaml
      request:
        method: GET
      response:
        status: OK
        body:
          payload:
            - 8070
        headers:
          X-Total-Count: 4
    """
```
The current behavior is that the last call will override the first but what i'm trying to say is that 
the first time we call the mock -> we get the response 1
The second call -> we get the second response
