### ISSUE TITLE
The ?in matcher checks the order instead of only checking value presence

### ISSUE THREAD

**Issue by Diartos** [Decathlon/tzatziki#567]
Hello,

I'm experiencing unexpected behavior with the ?in operator when checking values in my tests.

Context:
I have a test where I want to verify that the id values of my options are between 1 and 4, regardless of their order in the options list, since the list is shuffled on each run.

```
options:
- id: ?in [1, 2, 3, 4]
  content: Plumbers
  correct: true
- id: ?in [1, 2, 3, 4]
  content: Astronauts
  correct: false
- id: ?in [1, 2, 3, 4]
  content: Chefs
  correct: false
- id: ?in [1, 2, 3, 4]
  content: Architects
  correct: false
```

Problem:
When I use ?in [1, 2, 3, 4] for the id field, the test seems to check not only if each id is present in [1, 2, 3, 4], but also expects the order of the options in the list to match exactly. In other words, if the order of the options is different from the expected YAML, the test fails, even though all id values are valid.

On the other hand, if I use a matcher like ?gt 0 for the id, the check works as expected and does not depend on the order of the options.

Expected behavior:
The ?in operator should only check that each id value is present in the provided list, regardless of the order of the options themselves. The test should pass as long as all the ids are valid, no matter how the options are ordered.

Summary:
With ?in: the order of the options is checked, when it should not be.

With ?gt: works as expected, order is ignored.

Thank you in advance for your help and clarification!
